  ---
title: "Ymaze learning"
output: html_notebook
---

```{r }
library(readr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(tidyr)
library(stringr)
library(PairedData)
select = dplyr::select
library(viridis)
```

```{r}
px2pt = 1/(ggplot2::.pt*72.27/96)
gtheme = theme_minimal() + theme_cowplot() + 
  theme(text = element_text(size=8, family = 'Arial'), 
        panel.background = element_rect(fill = 'white'),
        line = element_line(size = px2pt),
        axis.line.x = element_line(size = 0.8 * px2pt, linetype = "solid", colour = "black"),
        axis.line.y = element_line(size = 0.8 * px2pt, linetype = "solid", colour = "black"),
        axis.text.x=element_text(size=8, colour = "black"),
        axis.text.y=element_text(size=8, colour = "black"),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8))
ymaze_results_dir = '~/Dropbox/phd/ymaze_chat_x_ai32/data/'
img_dir = '~/Dropbox/phd/ymaze_chat_x_ai32/img_gen/ymaze/'
```

```{r}
sem = function(x) sqrt( var(x, na.rm=TRUE) / length(x))
```

```{r}
df.raw = read_csv(paste0(ymaze_results_dir, 'learning_perf_stim.csv'))
df = gather(df.raw, 'mouse.id', 'correct', 2:ncol(df.raw)) %>%
  filter(!is.na(correct)) %>%
  filter(mouse.id != 0) %>%
  separate(mouse.id, c('cond', 'n', 'mouse.no'), sep='[_(]') %>%
  select(-n) %>%
  dplyr::mutate(mouse.no=ifelse(is.na(mouse.no),0,mouse.no),
                cond=str_trim(cond))

df$day = as.factor(df$day)
df$cond = as.factor(df$cond)
df$correct = as.integer(df$correct)
df$mouse.no = as.integer(df$mouse.no)
df$strain = 'ChAT-Ai32'
df = dplyr::mutate(df, strain_cond=paste(strain, cond))

#cond.cols = c('#440154ff', '#31688eff', '#6000ff98', '#35b779ff')
# colours for light conditions: no light, exploration througout, light at goal
cond.cols = c('#4d4d4dff',  '#b32300ff', '#35b779ff', '#0098ffff')

```

```{r}
levels.prev = levels(df$cond)
df$cond = factor(df$cond, levels=levels.prev[c(3,1,4,2)])
```

```{r}
df %>%
  ggplot() +
  geom_boxplot(aes(x=day, y=correct, colour=cond)) +
  scale_color_manual(values=cond.cols) +
  gtheme +
  theme(legend.position='top') +
  labs(colour='', fill='') +
  xlab('Day') + ylab('Correct (%)')
```

```{r}
df %>%
  dplyr::group_by(day, cond) %>%
  dplyr::summarise(mcorrect=mean(correct), semcorrect=sem(correct)) %>% 
  ggplot(aes(x=as.integer(day), y=mcorrect, group=cond)) +
  geom_line(aes(colour=cond, group=cond)) +
  geom_ribbon(aes(ymin=mcorrect-semcorrect, ymax=mcorrect+semcorrect, fill=cond), alpha=0.1) +
  geom_hline(yintercept = 80, linetype='dashed') +
  gtheme +
  scale_color_manual(values=cond.cols) +
  scale_fill_manual(values=cond.cols) +
  #theme(legend.position='none') +
  scale_x_continuous(breaks=1:7, limits=c(1,7))+
  labs(colour='', fill='') +
  xlab('Day') + ylab('Correct (%)')
ggsave(paste0(img_dir, 'learning_curve.pdf'), width=6, 
       height=6.5, unit='cm', dpi=300, device=cairo_pdf)
  
```



Reached learning criterion?
```{r}

which.day.learnt = function(correct_pct, learning.crit) {
  days=length(correct_pct):1
  for (day in days) {
    if (correct_pct[day] < learning.crit) {
      return(day+1)
    }
  }
  return(day)
}

df.learnt = df %>% 
  dplyr::group_by(cond, strain, strain_cond, mouse.no) %>%
  dplyr::arrange(day) %>%
  dplyr::summarise(learnt.90=which.day.learnt(correct, 90),
            learnt.80=which.day.learnt(correct, 80),
            learnt.70=which.day.learnt(correct, 70)) %>% 
  gather(key='criterion', value='learnt.day', 5:7)

df.learnt.80 = filter(df.learnt, criterion == 'learnt.80')
df.learnt.90 = filter(df.learnt, criterion == 'learnt.90')
```


```{r}
library(ggpubr)
df.learnt %>%
  filter(criterion == 'learnt.80') %>%
  #ggplot(aes(x=cond, y=learnt.day)) +
  #geom_boxplot(aes(colour=cond), outlier.size=0) +
  ggpubr::ggboxplot(x='cond', y='learnt.day', outlier.shape=NA) +
  geom_dotplot(aes(colour=cond), 
               binaxis="y", stackdir="center", fill=NA,
               binwidth=0.2, dotsize=1, stackratio=0.8, width=px2pt * 1) +
  stat_compare_means(aes(label = paste0('p=', ..p.format..)),
                     method='wilcox.test',
                     comparisons=list(c(1,3), c(1,4)),
                     label.y=c(6.5,7.4)) +
  gtheme +
  scale_color_manual(values=cond.cols) +
  #scale_fill_manual(values=cond.cols) +
  theme(axis.text.x=element_text(angle = 45, hjust = 1)) +
  xlab('') + ylab('Days until learned (≥ 80 %)') +
  theme(legend.position = 'none') 

ggsave(paste0(img_dir, 'learnt_boxplot.pdf'), width=5.6, 
       height=7.5, unit='cm', dpi=300, device=cairo_pdf)
```

```{r}
kruskal.test(learnt.day ~ cond, df.learnt, subset=criterion=='learnt.80')
library(FSA)
dunnTest(learnt.day ~ cond, df.learnt.80, method='none')
```

Tukey multiple comparisons of means test
```{r}
m.aov = aov(learnt.day ~ cond, df.learnt, subset=criterion=='learnt.80') 
summary(m.aov)
TukeyHSD(m.aov, 'cond')
```

```{r}
wtdf.raw = read_csv(paste0(ymaze_results_dir, 'wt_learning_perf.csv'))
wtdf = gather(wtdf.raw, 'mouse.id', 'correct', 2:ncol(wtdf.raw)) %>%
  filter(!is.na(correct)) %>%
  filter(mouse.id != 0) %>%
  separate(mouse.id, c('cond', 'n', 'mouse.no'), sep='[_(]') %>%
  select(-n) %>%
  mutate(mouse.no=ifelse(is.na(mouse.no),0,mouse.no),
         cond=str_trim(cond))

wtdf$day = as.factor(wtdf$day)
wtdf$cond = as.factor(wtdf$cond)
wtdf$cond = factor(wtdf$cond, levels=levels(wtdf$cond)[c(2,1)])
wtdf$correct = as.integer(wtdf$correct)
wtdf$mouse.no = as.integer(wtdf$mouse.no)
wtdf$strain = 'WT'
wtdf = dplyr::mutate(wtdf, strain_cond=paste(strain, cond))
wtdf$strain_cond = as.factor(wtdf$strain_cond)
wtdf$strain_cond = factor(wtdf$strain_cond, levels=levels(wtdf$strain_cond)[c(2,1)])

```

```{r}
wtdf %>%
  dplyr::group_by(day,cond) %>%
  dplyr::summarise(mcorrect=mean(correct), semcorrect=sem(correct)) %>%
  ggplot(aes(x=as.integer(day), y=mcorrect, group=cond)) +
  geom_line(aes(colour=cond, group=cond)) +
  #geom_point(aes(colour=cond, group=cond)) +
  #geom_errorbar(aes(ymin=mcorrect-semcorrect, ymax=mcorrect+semcorrect), width=0.2) +
  geom_ribbon(aes(ymin=mcorrect-semcorrect, ymax=mcorrect+semcorrect, fill=cond), alpha=0.1) +
  geom_hline(yintercept = 80, linetype='dashed') +
  gtheme +
  theme(legend.position='none') +
  scale_color_manual(values=c(cond.cols[1], cond.cols[4])) +
  scale_fill_manual(values=c(cond.cols[1], cond.cols[4])) +
  scale_x_continuous(breaks=1:7, limits=c(1,7))+
  labs(colour='', fill='') +
  xlab('Day') + ylab('Correct (%)')
ggsave(paste0(img_dir, 'wt_learning_curve.pdf'), width=6, 
       height=6.5, units='cm', dpi=300, device=cairo_pdf)
  
```

```{r}
wtdf.learnt = wtdf %>% 
  dplyr::group_by(cond, strain, strain_cond, mouse.no) %>%
  dplyr::arrange(day) %>%
  dplyr::summarise(learnt.day=which.day.learnt(correct, 80),
                   criterion='learnt.80')
```

```{r}
wtdf.learnt %>%
  #ggplot(aes(x=cond, y=learnt.day)) +
  #geom_boxplot(aes(colour=cond), outlier.size=0) +
  ggpubr::ggboxplot(x='cond', y='learnt.day', outlier.shape=NA) +
  geom_dotplot(aes(color=cond), 
               binaxis="y", stackdir="center", fill=NA, 
               binwidth=0.2, dotsize=1, stackratio=0.8, alpha=0.7) +
  stat_compare_means(aes(label = paste0('p=', ..p.format..)),
                     method='t.test',
                     comparisons=list(c(1,2))) +
  gtheme +
  theme(axis.text.x=element_text(angle = 30, hjust = 1)) +
  scale_color_manual(values=c(cond.cols[1], cond.cols[4])) +
  scale_fill_manual(values=c(cond.cols[1], cond.cols[4])) +
  xlab('') + ylab('Days until learned (≥ 80 %)') +
  ylim(c(1,7))+
  theme(legend.position = 'none') 

ggsave(paste0(img_dir, 'wtlearnt_boxplot.pdf'), width=5.5, 
       height=6, units='cm', dpi=300, device=cairo_pdf)

```
```{r}
shapiro.test(subset(wtdf.learnt, cond == 'No stim')$learnt.day)
shapiro.test(subset(wtdf.learnt, cond == 'Goal')$learnt.day)
t.test(learnt.day ~ cond, data=wtdf.learnt)
```
Joined ChAT and WT
```{r}
learnt.joined = bind_rows(wtdf.learnt, df.learnt.80)
levels.prev = levels(as.factor(learnt.joined$strain_cond))
learnt.joined$strain_cond = factor(learnt.joined$strain_cond, levels=levels.prev[c(3,1,4,2,6,5)])
strain.cond.cols = c(cond.cols, cond.cols[1], cond.cols[4])
learnt.joined$cond = as.factor(learnt.joined$cond)
learnt.joined$cond = factor(learnt.joined$cond, levels=levels(learnt.joined$cond)[c(3,1,4,2)])

learnt.joined %>%
  ggplot(aes(x=strain_cond, y=learnt.day)) +
  stat_summary(fun.y = median, fun.ymin = median, fun.ymax = median,
               geom = "crossbar", width = 0.6) +
  geom_dotplot(aes(color=cond), 
               binaxis="y", stackdir="center", fill=NA, 
               binwidth=0.2, dotsize=1, stackratio=0.8) +
  stat_compare_means(aes(label = paste0('p=', ..p.format..)),
                     method='t.test',
                     comparisons=list(c(1,3), c(1,4), c(4,6), c(4,5))) +
  scale_color_manual(values=strain.cond.cols) +
  gtheme +
  theme(axis.text.x=element_text(angle = 30, hjust = 1),
        legend.position = 'none') +
  scale_y_continuous(breaks=c(1, 3, 5, 7)) +
  xlab('') + ylab('Days until learned (≥ 80 %)')

ggsave(paste0(img_dir, 'joined_dotplot.pdf'), width=8, 
       height=6.5, units='cm', dpi=300, device=cairo_pdf)
```

```{r}
kruskal.test(learnt.day ~ strain_cond, learnt.joined)
dunnTest(learnt.day ~ strain_cond, learnt.joined, method='none')
```
```{r}
joined.summary.df = bind_rows(wtdf, df) %>% 
  dplyr::group_by(day, cond, strain_cond, strain) %>%
  dplyr::summarise(mcorrect=mean(correct), semcorrect=sem(correct)) 
joined.summary.df$cond = as.factor(joined.summary.df$cond)
joined.summary.df$cond = factor(joined.summary.df$cond, levels=levels(joined.summary.df$cond)[c(3,1,4,2)])

joined.summary.df %>%
  ggplot(aes(x=as.integer(day), y=mcorrect, group=strain_cond)) +
  geom_line(aes(colour=cond, group=strain_cond, linetype=strain)) +
  geom_ribbon(aes(ymin=mcorrect-semcorrect, ymax=mcorrect+semcorrect, fill=cond), alpha=0.1) +
  geom_hline(yintercept = 80, linetype='dashed') +
  gtheme +
  scale_color_manual(values=strain.cond.cols) +
  scale_fill_manual(values=strain.cond.cols) +
  #theme(legend.position='none') +
  scale_x_continuous(breaks=1:7, limits=c(1,7))+
  labs(colour='', fill='') +
  xlab('Day') + ylab('Correct (%)')
```

