function [] = sliderCallback(hObject, evt, vars)
    hObject.UserData.slider_pos = get(hObject,'Value');
	rec_len_sec = hObject.UserData.rec_len_sec;
    start_time_sec = (vars.lengthSeconds - rec_len_sec) * ...
        hObject.UserData.slider_pos;
    plotData(vars.fs, vars.data, vars.filtered, ...
             vars.ripple_starts, vars.ripple_ends, vars.normalizedSquaredSignal,...
             start_time_sec,...
             rec_len_sec);
end

