---
title: "R Notebook"
output: html_notebook
---
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(cowplot)
library(ggpubr)
library(purrr)
select = dplyr::select

library(lmerTest)
source('psd_analysis.R')
```

```{r}
data_dir =  '/mnt/DATA/chat_ripples/y-maze'
diode.signal = TRUE
if (diode.signal) {
  psddf.ymaze = read_csv(paste0(data_dir,'/','psd_table_diode_th6.csv'))
} else {
  psddf.ymaze = read_csv(paste0(data_dir,'/','psd_table_th6.csv'))  
}
psddf.ymaze = prepare.ymaze.df(psddf.ymaze)

trial.info.df = read_csv(paste(data_dir, 'trials.csv', sep='/')) %>%
  dplyr::mutate(file_name=paste0('signal/', animal, '_trial_', trial, '_g0'))
trial.info.df$date = as.Date(trial.info.df$date, '%d/%m/%Y')

psddf.ymaze = left_join(psddf.ymaze, dplyr::select(trial.info.df, -trial, -state, -laserOn), 
                        by=c('date', 'animal', 'file_name'))

freq.bands.df = data.frame(
  band=c('theta', 'slow gamma', 'fast gamma'),
  xmin=c(5, 25, 80),
  xmax=c(9, 45, 150)
)
```

# Effect of the task stage
```{r}
band.zscore = melt.freq.bands(filter(psddf.ymaze, correct==1), 
                             extra.id.vars=c('learning_day', 'dirname'),
                             psd.vars.prefix='all_psd_z_' ) %>%
  dplyr::rename(band.zscore=band_power)

psd.molten = melt.freq.bands(filter(psddf.ymaze, correct==1), 
                             extra.id.vars=c('learning_day', 'dirname'),
                             psd.vars.prefix='all_psd_xx_')
```


```{r}
axis.breaks=c(1:9,seq(10,100,10), 200)
axis.labels=rep('', length(axis.breaks))
axis.labels[1]=1
axis.labels[10]=10
axis.labels[19]=100
axis.labels[20]=200

band.zscore %>%
  filter(laserOn == 0) %>%
  #filter(animal == 'BS') %>%
  filter(learning_day == 6)  %>%
  filter(stage_desc %in% c('MazeStem', 'DuringStim')) %>%
  #filter(stage_desc %in% c('DuringStim')) %>%
  dplyr::mutate(trial_stage = paste0(trial_id, stage_desc, sep='_')) %>% 
  ggplot(aes(x=band_start_freq, y=band.zscore, group=trial_stage, color=stage_desc)) +
  geom_line(size=0.5*px2pt)  +
  facet_grid(laserOn ~ channelLocation) +
  scale_x_log10(limits=c(2,200), breaks=axis.breaks, labels=axis.labels) +
  geom_hline(yintercept = 0.0, linetype='dashed') +
  gtheme
```

```{r}
daily.band.zscore = band.zscore %>%
  group_by(channelLocation, date, learning_day, laserOn, stage_desc, band_start_freq) %>%
  dplyr::summarise(mean.zscore = mean(band.zscore),
                   sem.zscore = sem(band.zscore))

daily.band.zscore %>%
  filter(laserOn == 0) %>%
  #filter(animal == 'BS') %>%
  filter(learning_day == 6)  %>%
  filter(stage_desc %in% c('MazeStem', 'GoalZone20sec')) %>%
  #filter(stage_desc %in% c('MazeStem', 'AfterConsumedReward_10_sec')) %>%
  #dplyr::mutate(animal_stage = paste0(animal, stage_desc, sep='_')) %>% 
  ggplot(aes(x=band_start_freq, y=mean.zscore, group=stage_desc)) +
  geom_line(aes(color=stage_desc), size=2*px2pt) +
  geom_ribbon(aes(ymin=mean.zscore - sem.zscore, ymax=mean.zscore + sem.zscore), alpha=0.2) +
  facet_grid(. ~ channelLocation) +
  scale_x_log10(limits=c(2,200), breaks=axis.breaks, labels=axis.labels) +
  geom_hline(yintercept = 0.0, linetype='dashed') +
  gtheme +
  xlab('Frequency (Hz)') +
  ylab('Power z-score') 
```

```{r}
daily.band.zscore %>%
  dplyr::mutate(date_laser=paste(date, laserOn, sep='_')) %>%
  filter(learning_day >= 4)  %>%
  filter(stage_desc %in% c('GoalZone20sec')) %>%
  ggplot(aes(x=band_start_freq, y=mean.zscore, group=date_laser)) +
  geom_line(aes(color=laserOn), size=1*px2pt) +
  #geom_ribbon(aes(ymin=mean.zscore - sem.zscore, ymax=mean.zscore + sem.zscore), alpha=0.2) +
  facet_grid(. ~ channelLocation) +
  scale_x_log10(limits=c(2,200), breaks=axis.breaks, labels=axis.labels) +
  geom_hline(yintercept = 0.0, linetype='dashed') +
  gtheme
```
Effect of the stage on PSD
```{r}
animal.psd = psd.molten %>%
  group_by(animal, learning_day, channelLocation, laserOn, stage_desc, band_start_freq) %>%
  dplyr::summarise(mean.power = mean(log(band_power)),
                   sem.power = sem(log(band_power)))
```

```{r}
animal.psd %>%
  filter(laserOn == 0) %>%
  filter(learning_day==6) %>%
  filter(stage_desc %in% c('MazeStem', 'GoalZone20sec')) %>%
  ggplot(aes(x=band_start_freq, y=mean.power, group=stage_desc)) +
  geom_line(aes(color=stage_desc), size=2*px2pt) +
  geom_ribbon(aes(ymin=mean.power - sem.power, ymax=mean.power + sem.power), alpha=0.2) +
  facet_grid(animal ~ channelLocation) +
  scale_x_log10(limits=c(2,200), breaks=axis.breaks, labels=axis.labels) +
  geom_hline(yintercept = 0.0, linetype='dashed') +
  gtheme +
  xlab('Frequency (Hz)') +
  ylab('Power z-score') 
```
# Laser effect 


```{r}
animal.psd = psd.molten %>%
  filter(learning_day >= 5)  %>%
  group_by(animal, channelLocation, laserOn, stage_desc, band_start_freq) %>%
  dplyr::summarise(mean.power = mean(log(band_power)),
                   sem.power = sem(log(band_power)))
```


```{r}
animal.psd %>%
  #filter(stage_desc %in% c('DuringStim')) %>%
  filter(stage_desc %in% c('GoalZone20sec')) %>%
  dplyr::mutate(animal_laser = paste(animal, laserOn, sep='_')) %>%
  ggplot(aes(x=band_start_freq, y=mean.power, group=animal_laser)) +
  geom_line(aes(color=laserOn), size=1*px2pt) +
  geom_ribbon(aes(ymin=mean.power - sem.power, ymax=mean.power + sem.power), alpha=0.2) +
  facet_grid(animal ~ channelLocation) +
  scale_x_log10(limits=c(2,200), breaks=axis.breaks, labels=axis.labels) +
  #geom_hline(yintercept = 0.0, linetype='dashed') +
  gtheme +
  xlab('Frequency (Hz)') + ylab('Power (log)')
```

No change of power in ripple band.
```{r}
subset.psddf = filter(psddf.ymaze, learning_day == 6,
                      correct == 1,
                      channelLocation == 'CA3',
                      stage_desc == 'GoalZone20sec')

m.full = lmerTest::lmer(log(pow_ripple_band) ~ laserOn + (1 + laserOn | animal), data=subset.psddf, REML = TRUE) 
summary(m.full)
plot.model.diagnostics(m.full, subset.psddf$animal, subset.psddf$laserOn)
coef(m.full)$animal
anova(m.full, refit=FALSE, ddf='Satterthwaite')
```

# Coherence
```{r}
wcoh.df = read_csv(paste(data_dir, 'coherence_table.csv', sep='/'))
wcoh.df$animal = as.factor(wcoh.df$animal)
wcoh.df$laserOn = as.factor(wcoh.df$laserOn)
wcoh.df = wcoh.df %>%
  dplyr::mutate(trial_id=paste(date, animal, trial ,sep='_'))
wcoh.df$trial_id = as.factor(wcoh.df$trial_id)
wcoh.df$channelLocation = 'CA1-CA3'
```

```{r}
wcoh.molten = melt.freq.bands(wcoh.df, extra.id.vars = c('file_name'), psd.vars.prefix='all_coh_') %>%
  left_join(dplyr::select(trial.info.df, -trial, -state, -laserOn), 
            by=c('date', 'animal', 'file_name'))
```

```{r}
animal.stage.wcoh.df = wcoh.molten %>%
  filter(correct==1) %>%
  filter(learning_day>=5) %>%
  dplyr::group_by(animal, band_name, band_start_freq, laserOn, stage_desc) %>%
  dplyr::summarise(power.mean=mean(band_power, na.rm=TRUE),
                   power.sem=sem(band_power))

animal.stage.wcoh.df %>%
  filter(stage_desc == 'StimLast10sec') %>%
  #filter(stage_desc == 'GoalZone20sec') %>%
  dplyr::mutate(animal_laser=paste(animal, laserOn, sep='_')) %>%
  ggplot() +
  geom_line(aes(x=band_start_freq, group=animal_laser, y=power.mean, color=laserOn)) + 
  geom_ribbon(aes(x=band_start_freq, group=animal_laser, ymin=power.mean-power.sem, ymax=power.mean+power.sem),
              alpha=0.1) +
  geom_rect(data=freq.bands.df, mapping=aes(xmin=xmin, xmax=xmax, group=band), 
            ymin=-1, ymax=5, alpha=0.05, fill='grey10') +
  scale_x_log10(limits=c(1,150), breaks=axis.breaks, labels=axis.labels) +
  xlab('Frequency (Hz)') +
  ylab('Coherence') +
  facet_wrap(animal ~ ., ncol = 2) +
  gtheme +
  theme(legend.position = 'top')
```

Laser increased coherence in the ripple band...
What about just the epochs of ripples in the CA3?
```{r}
subset.wcoh.df = filter(wcoh.df, stage_desc == 'GoalZone20sec')
m.full = lmerTest::lmer(log(coh_ripple_band) ~ laserOn + (1 + laserOn | animal), data=subset.wcoh.df, REML = TRUE) 
summary(m.full)
plot.model.diagnostics(m.full, subset.wcoh.df$animal, subset.wcoh.df$laserOn)
coef(m.full)$animal
anova(m.full, refit=FALSE, ddf='Satterthwaite')
```
Create ratio of coherence and plot for each animal?
```{r}

```


TODO:
[] check coherence in ripple band during the epochs with ripples in CA3. 
[] Plot coherence in bands up to 250 Hz.
