total_trials = animals_dat1.Albert.ntrials + animals_dat2.Albert.ntrials + ...
    animals_dat3.Albert.ntrials + animals_dat4.Albert.ntrials + animals_dat5.Albert.ntrials + ...
    animals_dat6.Albert.ntrials + animals_dat7.Albert.ntrials + animals_dat8.Albert.ntrials;
wide_psd = animals_dat1.Albert.wide_psd + animals_dat2.Albert.wide_psd + animals_dat3.Albert.wide_psd + animals_dat4.Albert.wide_psd + ...
    animals_dat5.Albert.wide_psd + animals_dat6.Albert.wide_psd + animals_dat7.Albert.wide_psd + animals_dat8.Albert.wide_psd;
wide_psd = wide_psd / total_trials;
wide_psdtable = psd2table(wide_psd, animals_dat1.Albert.psd_wide_bands, key_position_names);
all_psd = animals_dat1.Albert.all_psd + animals_dat2.Albert.all_psd + animals_dat3.Albert.all_psd + animals_dat4.Albert.all_psd + ...
    animals_dat5.Albert.all_psd + animals_dat6.Albert.all_psd + animals_dat7.Albert.all_psd + animals_dat8.Albert.all_psd;
all_psd = all_psd / total_trials;
all_psdtable = psd2table(all_psd, animals_dat1.Albert.psd_all_bands, key_position_names);

writetable(psd2table(animals_dat1.Albert.wide_psd / animals_dat1.Albert.ntrials, animals_dat1.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert1.csv');
writetable(psd2table(animals_dat2.Albert.wide_psd / animals_dat2.Albert.ntrials, animals_dat2.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert2.csv');
writetable(psd2table(animals_dat3.Albert.wide_psd / animals_dat3.Albert.ntrials, animals_dat3.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert3.csv');
writetable(psd2table(animals_dat4.Albert.wide_psd / animals_dat4.Albert.ntrials, animals_dat4.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert4.csv');
writetable(psd2table(animals_dat5.Albert.wide_psd / animals_dat5.Albert.ntrials, animals_dat5.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert5.csv');
writetable(psd2table(animals_dat6.Albert.wide_psd / animals_dat6.Albert.ntrials, animals_dat6.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert6.csv');
writetable(psd2table(animals_dat7.Albert.wide_psd / animals_dat7.Albert.ntrials, animals_dat6.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert7.csv');
writetable(psd2table(animals_dat8.Albert.wide_psd / animals_dat8.Albert.ntrials, animals_dat8.Albert.psd_wide_bands, key_position_names),...
    'wide_psd_albert8.csv');

writetable(wide_psdtable, 'wide_psd_albert.csv');
writetable(all_psdtable, 'all_psd_albert.csv');

% 
% total_trials = animals_dat1.Nigel.ntrials + animals_dat2.Nigel.ntrials + animals_dat3.Nigel.ntrials + animals_dat4.Nigel.ntrials + ...
%     animals_dat5.Nigel.ntrials + animals_dat6.Nigel.ntrials + animals_dat7.Nigel.ntrials + animals_dat8.Nigel.ntrials;
% wide_psd = animals_dat1.Nigel.wide_psd + animals_dat2.Nigel.wide_psd + animals_dat3.Nigel.wide_psd + animals_dat4.Nigel.wide_psd + ...
%     animals_dat5.Nigel.wide_psd + animals_dat6.Nigel.wide_psd + animals_dat7.Nigel.wide_psd + animals_dat8.Nigel.wide_psd;
% wide_psd = wide_psd / total_trials;
% wide_psdtable = psd2table(wide_psd, animals_dat1.Nigel.psd_wide_bands, key_position_names);
% all_psd = animals_dat1.Nigel.all_psd + animals_dat2.Nigel.all_psd + animals_dat3.Nigel.all_psd + animals_dat4.Nigel.all_psd + ...
%     animals_dat5.Nigel.all_psd + animals_dat6.Nigel.all_psd + animals_dat7.Nigel.all_psd + animals_dat8.Nigel.all_psd;
% all_psd = all_psd / total_trials;
% all_psdtable = psd2table(all_psd, animals_dat1.Nigel.psd_all_bands, key_position_names);
% 
% writetable(wide_psdtable, 'nigel_wide_psd.csv');
% writetable(all_psdtable, 'nigel_all_psd.csv');
% 
% writetable(psd2table(animals_dat1.Nigel.wide_psd / animals_dat1.Nigel.ntrials, animals_dat1.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel1.csv');
% writetable(psd2table(animals_dat2.Nigel.wide_psd / animals_dat2.Nigel.ntrials, animals_dat2.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel2.csv');
% writetable(psd2table(animals_dat3.Nigel.wide_psd / animals_dat3.Nigel.ntrials, animals_dat3.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel3.csv');
% writetable(psd2table(animals_dat4.Nigel.wide_psd / animals_dat4.Nigel.ntrials, animals_dat4.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel4.csv');
% writetable(psd2table(animals_dat5.Nigel.wide_psd / animals_dat5.Nigel.ntrials, animals_dat5.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel5.csv');
% writetable(psd2table(animals_dat6.Nigel.wide_psd / animals_dat6.Nigel.ntrials, animals_dat6.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel6.csv');
% writetable(psd2table(animals_dat7.Nigel.wide_psd / animals_dat7.Nigel.ntrials, animals_dat6.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel7.csv');
% writetable(psd2table(animals_dat8.Nigel.wide_psd / animals_dat8.Nigel.ntrials, animals_dat8.Nigel.psd_wide_bands, key_position_names),...
%     'wide_psd_Nigel8.csv');


function psd_table = psd2table(psd_dat, freq_bands, key_position_names)
    psd_table = array2table(psd_dat);
    psd_table.Properties.VariableNames = key_position_names;
    psd_table.freqs_start = freq_bands(1:end-1)';
    psd_table.freqs_end = freq_bands(2:end)';
end